//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringStreamService.Consumer.StringStreamServiceNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringStreamServiceNS.IStringStreamService")]
    public interface IStringStreamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/BeginStream", ReplyAction="http://tempuri.org/IStringStreamService/BeginStreamResponse")]
        System.Guid BeginStream();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/BeginStream", ReplyAction="http://tempuri.org/IStringStreamService/BeginStreamResponse")]
        System.Threading.Tasks.Task<System.Guid> BeginStreamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/PutStreamData", ReplyAction="http://tempuri.org/IStringStreamService/PutStreamDataResponse")]
        void PutStreamData(System.Guid streamId, string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/PutStreamData", ReplyAction="http://tempuri.org/IStringStreamService/PutStreamDataResponse")]
        System.Threading.Tasks.Task PutStreamDataAsync(System.Guid streamId, string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/GetSortedStream", ReplyAction="http://tempuri.org/IStringStreamService/GetSortedStreamResponse")]
        string[] GetSortedStream(System.Guid streamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/GetSortedStream", ReplyAction="http://tempuri.org/IStringStreamService/GetSortedStreamResponse")]
        System.Threading.Tasks.Task<string[]> GetSortedStreamAsync(System.Guid streamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/EndStream", ReplyAction="http://tempuri.org/IStringStreamService/EndStreamResponse")]
        void EndStream(System.Guid streamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringStreamService/EndStream", ReplyAction="http://tempuri.org/IStringStreamService/EndStreamResponse")]
        System.Threading.Tasks.Task EndStreamAsync(System.Guid streamId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringStreamServiceChannel : StringStreamService.Consumer.StringStreamServiceNS.IStringStreamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringStreamServiceClient : System.ServiceModel.ClientBase<StringStreamService.Consumer.StringStreamServiceNS.IStringStreamService>, StringStreamService.Consumer.StringStreamServiceNS.IStringStreamService {
        
        public StringStreamServiceClient() {
        }
        
        public StringStreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringStreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringStreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid BeginStream() {
            return base.Channel.BeginStream();
        }
        
        public System.Threading.Tasks.Task<System.Guid> BeginStreamAsync() {
            return base.Channel.BeginStreamAsync();
        }
        
        public void PutStreamData(System.Guid streamId, string[] text) {
            base.Channel.PutStreamData(streamId, text);
        }
        
        public System.Threading.Tasks.Task PutStreamDataAsync(System.Guid streamId, string[] text) {
            return base.Channel.PutStreamDataAsync(streamId, text);
        }
        
        public string[] GetSortedStream(System.Guid streamId) {
            return base.Channel.GetSortedStream(streamId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSortedStreamAsync(System.Guid streamId) {
            return base.Channel.GetSortedStreamAsync(streamId);
        }
        
        public void EndStream(System.Guid streamId) {
            base.Channel.EndStream(streamId);
        }
        
        public System.Threading.Tasks.Task EndStreamAsync(System.Guid streamId) {
            return base.Channel.EndStreamAsync(streamId);
        }
    }
}
